= LedUtil Library for Arduino =

This library allows you to control a LED. For each instantiated object it is possible to control only one key. The "liga" method using to turn on a LED. The "desliga" method using to turn off a LED. The "pisca" method apply blink effect on LED.  


For more information about this library please visit us at
https://github.com/pacocatech/LedUtil

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
